### ISSUE TITLE
[dev EquipmentAPI] erro nas migrations - docker-compose up

### ISSUE THREAD

**Issue by ErickGiffoni** [fga-eps-mds/2022-2-Alectrion-DOC#109]
**Descrever o bug**
A _migration_ `default1674611694082` falhou durante a execução do docker-compose

**Como reproduzir o bug**
No repositório EquipmentAPI:
1. Esteja na _branch_ "dev" no _commit_ [6fda11ec82f46dd913e8bd2ea7c220092e12e590](https://github.com/fga-eps-mds/2022-2-Alectrion-EquipamentApi/commit/6fda11ec82f46dd913e8bd2ea7c220092e12e590)2. 
2. Faça `docker-compose up`
3. Visualize os erros

**Comportamento Esperado**
O _container_ deveria subir corretamente, sem erros

**Screenshots / Captura de tela**

**Desktop / computadores (informe as características do computador utilizado):**
 - Sistema Operacional: macOS
 - Plataforma: Docker
   - Versão: 4.8.1 (78998)
   - Engine: 20.10.14

**Informações adicionais**
Log do primeiro erro (foi um atrás do outro enquanto eu ia corrigindo => sim já corrigi e pretendo subir um PR de **hotfix** da _migration_):
```
equip_api_1  | query failed: CREATE TABLE "equipment_brand" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_ba1f5659893d908eaabb38453a6" PRIMARY KEY ("id"))
equip_api_1  | error: error: relation "equipment_brand" already exists
equip_api_1  |     at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
equip_api_1  |     at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
equip_api_1  |     at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
equip_api_1  |     at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
equip_api_1  |     at Socket.emit (node:events:513:28)
equip_api_1  |     at addChunk (node:internal/streams/readable:324:12)
equip_api_1  |     at readableAddChunk (node:internal/streams/readable:297:9)
equip_api_1  |     at Socket.Readable.push (node:internal/streams/readable:234:10)
equip_api_1  |     at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
equip_api_1  |   length: 109,
equip_api_1  |   severity: 'ERROR',
equip_api_1  |   code: '42P07',
equip_api_1  |   detail: undefined,
equip_api_1  |   hint: undefined,
equip_api_1  |   position: undefined,
equip_api_1  |   internalPosition: undefined,
equip_api_1  |   internalQuery: undefined,
equip_api_1  |   where: undefined,
equip_api_1  |   schema: undefined,
equip_api_1  |   table: undefined,
equip_api_1  |   column: undefined,
equip_api_1  |   dataType: undefined,
equip_api_1  |   constraint: undefined,
equip_api_1  |   file: 'heap.c',
equip_api_1  |   line: '1200',
equip_api_1  |   routine: 'heap_create_with_catalog'
equip_api_1  | }
equip_api_1  | Migration "default1674611694082" failed, error: relation "equipment_brand" already exists
equip_api_1  | query: ROLLBACK
equip_api_1  | Error during migration run:
equip_api_1  | QueryFailedError: relation "equipment_brand" already exists
equip_api_1  |     at PostgresQueryRunner.query (/app/src/driver/postgres/PostgresQueryRunner.ts:299:19)
equip_api_1  |     at processTicksAndRejections (node:internal/process/task_queues:95:5) {
equip_api_1  |   query: 'CREATE TABLE "equipment_brand" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, CONSTRAINT "PK_ba1f5659893d908eaabb38453a6" PRIMARY KEY ("id"))',
equip_api_1  |   parameters: undefined,
equip_api_1  |   driverError: error: relation "equipment_brand" already exists
equip_api_1  |       at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)
equip_api_1  |       at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)
equip_api_1  |       at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)
equip_api_1  |       at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)
equip_api_1  |       at Socket.emit (node:events:513:28)
equip_api_1  |       at addChunk (node:internal/streams/readable:324:12)
equip_api_1  |       at readableAddChunk (node:internal/streams/readable:297:9)
equip_api_1  |       at Socket.Readable.push (node:internal/streams/readable:234:10)
equip_api_1  |       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
equip_api_1  |     length: 109,
equip_api_1  |     severity: 'ERROR',
equip_api_1  |     code: '42P07',
equip_api_1  |     detail: undefined,
equip_api_1  |     hint: undefined,
equip_api_1  |     position: undefined,
equip_api_1  |     internalPosition: undefined,
equip_api_1  |     internalQuery: undefined,
equip_api_1  |     where: undefined,
equip_api_1  |     schema: undefined,
equip_api_1  |     table: undefined,
equip_api_1  |     column: undefined,
equip_api_1  |     dataType: undefined,
equip_api_1  |     constraint: undefined,
equip_api_1  |     file: 'heap.c',
equip_api_1  |     line: '1200',
equip_api_1  |     routine: 'heap_create_with_catalog'
equip_api_1  |   },
equip_api_1  |   length: 109,
equip_api_1  |   severity: 'ERROR',
equip_api_1  |   code: '42P07',
equip_api_1  |   detail: undefined,
equip_api_1  |   hint: undefined,
equip_api_1  |   position: undefined,
equip_api_1  |   internalPosition: undefined,
equip_api_1  |   internalQuery: undefined,
equip_api_1  |   where: undefined,
equip_api_1  |   schema: undefined,
equip_api_1  |   table: undefined,
equip_api_1  |   column: undefined,
equip_api_1  |   dataType: undefined,
equip_api_1  |   constraint: undefined,
equip_api_1  |   file: 'heap.c',
equip_api_1  |   line: '1200',
equip_api_1  |   routine: 'heap_create_with_catalog'
equip_api_1  | }
equip_api_1  | npm notice 
equip_api_1  | npm notice New major version of npm available! 8.19.3 -> 9.4.0
equip_api_1  | npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.4.0>
equip_api_1  | npm notice Run `npm install -g npm@9.4.0` to update!
equip_api_1  | npm notice 
equip_api_1  | error Command failed with exit code 1.
equip_api_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2022-2-alectrion-equipamentapi_equip_api_1 exited with code 1
```

**Comment by ErickGiffoni** [comment]
Outra possível solução: excluir a pasta `data` na raiz do repositório do equipment

**Comment by ErickGiffoni** [comment]
Foi feito _commit_ de uma solução paliativa na _branch_ `hotfix/109-equipment-migrations` no repositório EquipmentAPI
